// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYeAY-c2ZdWIb1q7XJgd4Mt5V7VnD_L9k',
    appId: '1:224499335698:web:0a85f7441ff2fb22f14ecb',
    messagingSenderId: '224499335698',
    projectId: 'forbmt',
    authDomain: 'forbmt.firebaseapp.com',
    storageBucket: 'forbmt.appspot.com',
    measurementId: 'G-DBRNDFDQ4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYtnzrPnBs4SyZXIHJDLqKLchnxOUUrYU',
    appId: '1:224499335698:android:664292631d1c54a9f14ecb',
    messagingSenderId: '224499335698',
    projectId: 'forbmt',
    storageBucket: 'forbmt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCO_9JyABE571gDwRHsbQWgJ7OTLDf9CQ',
    appId: '1:224499335698:ios:dcc4c9b1fac12b42f14ecb',
    messagingSenderId: '224499335698',
    projectId: 'forbmt',
    storageBucket: 'forbmt.appspot.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCO_9JyABE571gDwRHsbQWgJ7OTLDf9CQ',
    appId: '1:224499335698:ios:765c61c700f48753f14ecb',
    messagingSenderId: '224499335698',
    projectId: 'forbmt',
    storageBucket: 'forbmt.appspot.com',
    iosBundleId: 'com.example.test1.RunnerTests',
  );
}
